apiVersion: v1
kind: Secret
metadata:
  name: simple-superset-credentials
type: Opaque
stringData:
  adminUser.username: superset
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: admin
  connections.secretKey: thisISaSECRET_1234
  # The information provided here (regarding database, username and password) needs to line up with your helm values
  connections.sqlalchemyDatabaseUri: postgresql://superset:pw123@pg-superset-postgresql-hl/superset
---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: simple-superset
spec:
  image:
    productVersion: 3.0.1
  clusterConfig:
    credentialsSecret: simple-superset-credentials
    listenerClass: external-unstable
  nodes:
    roleGroups:
      default:
        replicas: 1